## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
notifications:
  email: false
git:
  depth: 99999999
before-install:
  - sudo apt-get install curl
script:
  - julia -e 'import Pkg; Pkg.dev(Pkg.PackageSpec(url=pwd()));'
  - julia -e 'import Pkg; Pkg.build("Mosek");'
  - julia -e 'import Pkg; Pkg.test("Mosek");'

after_success:
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'import Mosek; cd(dirname(dirname(pathof(Mosek)))); include(joinpath("docs", "make.jl"))'
