name = "Mosek"
uuid = "6405355b-0ac2-5fba-af84-adbd65488c0e"
repo = "https://github.com/JuliaOpt/Mosek.jl.git"
version = "0.9.9"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MathProgBase = "0.7.2"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
