name = "Mosek"
uuid = "6405355b-0ac2-5fba-af84-adbd65488c0e"
repo = "https://github.com/JuliaOpt/Mosek.jl.git"
version = "1.1.3"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
WinReg = "1b915085-20d7-51cf-bf83-8f477d6f5128"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
